### PR TITLE
Changes to support granular permissions in the definition of the app registration/enterprise app

### PR DESCRIPTION
**Pull request by joeharlan**
# Description

The changes included in this PR are provided to augment the definition of the Entra ID App Registration and its Enterprise App (Security Principal) to include the delegated permission grants for the required API's in support of the Zero Trust Granular Permissions feature of Rubrik Security Cloud for Azure Cloud Native Protection.

## Related Issue

This project only accepts pull requests related to open issues.

* If suggesting a new feature or change, please discuss it in an issue first.
* If fixing a bug, there should be an issue describing it with steps to reproduce

[_Please link to the issue here_](https://github.com/rubrikinc/terraform-provider-polaris/issues/137)

## Motivation and Context

These changes follow the Rubrik Security Cloud User's Guide in terms of the requirements for manual configuration of the App Registration/Enterprise App (Security Principal) for use in the Onboarding without OAuth method.
https://docs.rubrik.com/en-us/saas/saas/prereq_azr_cld_acnt_without_oauth.html

## How Has This Been Tested?

This approach has been tested in the Trinity and Oasis labs as well as with at least two customers to date.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG file accordingly for the version that this merge modifies.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DamaniN — APPROVED** [review]
Looks good by visual inspection. I did not get a chance to run and test this.

See next comment for review questions about upgrades.

**Review by DamaniN — CHANGES_REQUESTED** [review]
@joeharlan, did you test this as an upgrade to an existing configuration? Will the changes to things like the display name cause the SP to be removed and re-added? Such a change could break an existing RSC implementation.

**Comment by joeharlan** [comment]
@DamaniN The one change sure to break in the way you described is the one that shifts from using a SP password to using an App Registration password: https://github.com/rubrikinc/terraform-azure-polaris-cloud-native_tenant/pull/4/commits/56097fe524e433fa803f8a184d5c8f4c12033438

In this area I remain somewhat conflicted.  General guidance for use of a secret on an App Registration versus on its associated Security Principal (Enterprise App) is not clear to me.  

Rubrik user docs for this aspect of the configuration clearly requests an App Registration password, but in some recent research I have learned this placement of the secret is best for cross-tenant use cases which Rubrik does not require.  Some writings on the subject even suggests that the SP password is a more secure single-tenant option that aligns best to automation and secret rotation requirements.  With that in mind, I now want to lean that way.

I think we need Engineering to make a call here so we do not assume the wrong path.  In all of my testing I have used the App Registration password and it appears to work for all intents and purposes.

I will revert this change for now to avoid any breaking changes it is likely to introduce with previous module users and we can await word from Engineering before deciding whether to change it later.

**Review by DamaniN — APPROVED** [review]
LGTM

**Pull request merged**
